lenmus/lomse

CHANGELOG.md, src/graphic_model/layouters/lomse_score_layouter.cpp, test-scores/01032-tie-bezier-break.lms
Now fixed. Also fixed test score 01032, because newSytem tag was not placed in proper location.
=> Fixes #1 new sytem tags not working properly

CHANGELOG.md, include/lomse_ldp_elements.h, src/exporters/lomse_ldp_exporter.cpp, src/parser/ldp/lomse_ldp_analyser.cpp, src/parser/lomse_ldp_factory.cpp, src/tests/lomse_test_ldp_analyser.cpp, src/tests/lomse_test_ldp_exporter.cpp, test-scores/00041-all-notes-proportional-spacing.lms, test-scores/00042-all-notes-dotted.lms, test-scores/00043-all-notes-double-dotted.lms, test-scores/00044-all-notes-triple-dotted.lms, test-scores/02070-dynamics-marks.lms
All the infrastructure was already in Lomse, as it was created for importing MusicXML. This PR just improves the LDP Analyser and Exporter so that dynamics marks can be also used in LDP.
=> Add support in LDP for dynamics marks (analyser and exporter)

CHANGELOG.md, include/lomse_score_layouter.h, include/lomse_staffobjs_cursor.h, src/graphic_model/engravers/lomse_time_engraver.cpp, src/graphic_model/layouters/lomse_score_layouter.cpp, src/graphic_model/layouters/lomse_spacing_algorithm.cpp, src/graphic_model/layouters/lomse_spacing_algorithm_gourlay.cpp, src/graphic_model/layouters/lomse_staffobjs_cursor.cpp, src/tests/lomse_test_column_breaker.cpp, src/tests/lomse_test_spacing_algorithm.cpp, test-scores/00120-time-signatures.lms
For special scores, such as scores without time signature, the current line break algorithm need to be improved. This PR introduces initial changes aimed at this objective.
=> Changes to use different break modes in line breaker algorithm

CHANGELOG.md, include/lomse_internal_model.h, include/lomse_midi_table.h, src/internal_model/lomse_internal_model.cpp, src/sound/lomse_midi_table.cpp, src/sound/lomse_score_player.cpp, src/tests/lomse_test_internal_model.cpp, src/tests/lomse_test_midi_table.cpp
* Refactored some code related to this bug, to improve
understandability and maintenace.
* Added unit test.
=> Fix issue #69: Playback very slow for 3/8 tempo

CHANGELOG.md, add-sources.cmake, include/lomse_autoclef.h, include/lomse_document.h, include/lomse_staffobjs_cursor.h, src/document/lomse_document.cpp, src/graphic_model/layouters/lomse_staffobjs_cursor.cpp, src/parser/lomse_autoclef.cpp, src/tests/lomse_test_autoclef.cpp, src/tests/lomse_test_document.cpp, src/tests/lomse_test_mxl_analyser.cpp
* Added class AutoClef for enclosing the algorithm for issue #68.
* Added a few of helper methods in StaffObjsCursor.
* Added unit tests for AutoClef class.
=> Fix issue #68: Assume some default value for clef in MusicXML importer

.travis.yml
Fixes #129: e-mail notifications from travis builds
=> Fix e-mail notifications from travis builds

scripts/build-lomse.sh, src/graphic_model/layouters/lomse_document_layouter.cpp, src/mvc/lomse_presenter.cpp
- Accept also files with 'musicxml' extension
- Fix crash when layout error 'not enough space for just one system' (ActorPreludeSample)
=> Fixes for errors related to MusicXML files

include/lomse_internal_model.h
In this PR `boost::variant` is replaced with **union class**.
Along with plain types (int, float) the union needs to hold objects too (string, Color). This requires using of **placement new** and **explicit destructor calls** as explained in [Union declaration](http://en.cppreference.com/w/cpp/language/union) (cppreference.com).
=> Replaced boost::variant with union class

include/lomse_command.h, src/document/lomse_command.cpp, src/tests/lomse_test_command.cpp, src/tests/lomse_test_ldp_analyser.cpp, src/tests/lomse_test_ldp_exporter.cpp, src/tests/lomse_test_staffobjs_table.cpp
This PR also includes some changes for updating cursor in edition commands
=>  Fix all test failures when LOMSE_COMPATIBILITY_LDP_1_5 is OFF 

include/lomse_tree.h, src/graphic_model/engravers/lomse_dynamics_mark_engraver.cpp, src/graphic_model/layouters/lomse_score_layouter.cpp, src/graphic_model/lomse_shapes_storage.cpp, src/parser/ldp/lomse_ldp_analyser.cpp, src/parser/mnx/lomse_mnx_analyser.cpp, src/parser/mxl/lomse_mxl_analyser.cpp
Most of the issues were just cosmetic changes. But a couple of them were real bugs (using operator ~ instead of !).
=> Fix issues detected with GCC 7

LICENSE, include/lomse_graphic_view.h, scripts/build-api-docs.sh, scripts/build-lomse.sh, scripts/install-lomse.sh, src/mvc/lomse_graphic_view.cpp, src/tests/lomse_test_ldp_exporter.cpp
Auto-scroll did a lot of unnecessary jumps. The algorithm has been reviewed.
=> Improve auto-scroll algorithm

include/lomse_timegrid_table.h, src/graphic_model/lomse_box_system.cpp, src/graphic_model/lomse_caret_positioner.cpp, src/graphic_model/lomse_timegrid_table.cpp, src/tests/lomse_test_graphic_model.cpp
=> Interpolate x positions in TimeGridTable

src/graphic_model/layouters/lomse_spacing_algorithm_gourlay.cpp, src/tests/lomse_test_graphic_model.cpp
=> Fix error in TimeGridTable computation

CHANGELOG.md, include/lomse_engraving_options.h, include/lomse_spacing_algorithm_gourlay.h, src/graphic_model/layouters/lomse_spacing_algorithm_gourlay.cpp, test-scores/00622-non-timed-in-other-line.lms, test-scores/00623-clef-change-lyrics.xml, test-scores/00624-clef-change-accidental-lyrics.lms, test-scores/00625-spacer-lyrics.lms, test-scores/00626-lyrics-min-separation.lms
A few changes in spacing algorithm for improving management of lyrics
=> Improve spacing when there are lyrics

packages/pugixml/pugiconfig.hpp, packages/pugixml/pugixml.cpp, packages/pugixml/pugixml.hpp
Updated to latest codebase (commit 273fa0a) for removing Coverity scan issue in pugixml.
=> Update pugixml package. Fix high impact Coverity issue

CHANGELOG.md, add-sources.cmake, include/lomse_engraving_options.h, include/lomse_gm_basic.h, include/lomse_internal_model.h, include/lomse_mxl_analyser.h, include/lomse_shape_wedge.h, include/lomse_wedge_engraver.h, src/exporters/lomse_ldp_exporter.cpp, src/graphic_model/engravers/lomse_barline_engraver.cpp, src/graphic_model/engravers/lomse_wedge_engraver.cpp, src/graphic_model/layouters/lomse_score_layouter.cpp, src/graphic_model/layouters/lomse_spacing_algorithm_gourlay.cpp, src/graphic_model/lomse_box_system.cpp, src/graphic_model/lomse_fragment_mark.cpp, src/graphic_model/lomse_gm_basic.cpp, src/graphic_model/lomse_shape_wedge.cpp, src/internal_model/lomse_im_factory.cpp, src/internal_model/lomse_internal_model.cpp, src/parser/lomse_linker.cpp, src/parser/mxl/lomse_mxl_analyser.cpp, src/tests/lomse_test_mxl_analyser.cpp, test-scores/50040-wedge.xml
This PR adds support for crescendo/diminuendo wedges and modifies the MusicXML importer so that now the wedges are imported and rendered.
=> Import and render crescendo/diminuendo wedges

include/lomse_mnx_analyser.h, src/parser/mnx/lomse_mnx_analyser.cpp, src/tests/lomse_test_mnx_analyser.cpp
This PR implements the parsing of `<global>` elements so that the importer now correctly deals with all MNX samples in the MNX-Common By Example page.
Some time ago I started the development of a tentative MNX importer, to be refined as the MNX standard is defined. The objective was to advance the work to support MNX, so that the importer could be ready when the standard is published. And to provide feedback to the W3C Working Group based not only on theoretical considerations but also on practical issues found when implementing the proposed drafts.
=> Process <global> elements in MNX

add-sources.cmake, include/lomse_engravers_map.h, include/lomse_note_engraver.h, include/lomse_noterest_engraver.h, include/lomse_rest_engraver.h, include/lomse_score_layouter.h, include/lomse_spacing_algorithm.h, include/lomse_spacing_algorithm_gourlay.h, include/lomse_system_layouter.h, src/graphic_model/engravers/lomse_note_engraver.cpp, src/graphic_model/engravers/lomse_noterest_engraver.cpp, src/graphic_model/engravers/lomse_rest_engraver.cpp, src/graphic_model/layouters/lomse_score_layouter.cpp, src/graphic_model/layouters/lomse_spacing_algorithm.cpp, src/graphic_model/layouters/lomse_spacing_algorithm_gourlay.cpp, src/graphic_model/layouters/lomse_system_layouter.cpp, src/graphic_model/lomse_engravers_map.cpp, src/tests/lomse_test_beam_engraver.cpp, src/tests/lomse_test_chord_engraver.cpp, src/tests/lomse_test_note_engraver.cpp, src/tests/lomse_test_rest_engraver.cpp, src/tests/lomse_test_shapes.cpp, src/tests/lomse_test_spacing_algorithm.cpp, src/tests/lomse_test_tuplet_engraver.cpp
Rename object so that it is coherent with its function and remove no longer needed, unused code.
=> Rename ShapesStorage as EngraversMap and remove unused code

include/lomse_graphic_view.h, include/private/lomse_internal_model_p.h, src/graphic_model/layouters/lomse_score_meter.cpp, src/internal_model/lomse_api_internal_model.cpp, src/internal_model/lomse_internal_model.cpp, src/parser/ldp/lomse_ldp_analyser.cpp, src/parser/lmd/lomse_lmd_analyser.cpp, src/parser/mnx/lomse_mnx_analyser.cpp, src/parser/mxl/lomse_mxl_analyser.cpp, src/tests/lomse_test_autoclef.cpp, src/tests/lomse_test_document.cpp, src/tests/lomse_test_im_visitor.cpp, src/tests/lomse_test_internal_model.cpp, src/tests/lomse_test_staffobjs_table.cpp
Usefull to fine tune appearance
=> Add LDP option for controlling spacing algorithm, parameter Dmin

src/file_system/lomse_image_reader.cpp, src/graphic_model/layouters/lomse_table_layouter.cpp, src/graphic_model/lomse_overlays_generator.cpp, src/sound/lomse_score_player.cpp
I have enabled Code  Scanning to see if it is worth using it.
=> Fix alerts detected by GitHub's Code Scanning

include/lomse_relation_builder.h, src/parser/mxl/lomse_mxl_analyser.cpp, src/tests/lomse_test_mxl_analyser.cpp
This PR fixes the MusicXML importer so that now it will import slurs in which the end of the slur is found in the MusicXML file before the start of the slur. This can happen when the start of the slur is in a different voice than the end of the slur.
It also fixes a bug detected in slur Id assignment, that also existed in volta brackets and octave shifts.
=> MusicXML: slur end can be found before slur start

include/private/lomse_document_p.h, src/document/lomse_command.cpp, src/document/lomse_document.cpp, src/graphic_model/engravers/lomse_chord_engraver.cpp, src/tests/lomse_test_doc_model.cpp
In the previous PR I forgot to upload a test file that is now included in this PR. Also, to clean up the `Document` class: remove a member variable that is no longer used and a couple of methods related to it.
=> Add missing test file and clean up Document class
