CHANGELOG.md
include/lomse_engraving_options.h
include/lomse_gm_basic.h
include/lomse_instrument_engraver.h
include/lomse_internal_model.h
include/lomse_mxl_analyser.h
include/lomse_shape_brace_bracket.h
include/lomse_shape_staff.h
src/graphic_model/engravers/lomse_instrument_engraver.cpp
src/graphic_model/layouters/lomse_score_layouter.cpp
src/graphic_model/layouters/lomse_system_layouter.cpp
src/graphic_model/lomse_gm_basic.cpp
src/graphic_model/lomse_shape_brace_bracket.cpp
src/internal_model/lomse_internal_model.cpp
src/parser/ldp/lomse_ldp_analyser.cpp
src/parser/lmd/lomse_lmd_analyser.cpp
src/parser/mxl/lomse_mxl_analyser.cpp
src/tests/lomse_test_document_layouter.cpp
src/tests/lomse_test_ldp_analyser.cpp
src/tests/lomse_test_lmd_analyser.cpp
src/tests/lomse_test_mxl_analyser.cpp
test-scores/00224-all-group-styles.lmd

Several changes for improving the layout of groups of instruments:
- Barlines now can be joined. Mensurstrich layout also supported.
- Draw left barline at start of systems also in empty scores
- Added squared bracket for part groups (group symbol == line)
Whith this PR groups of instruments should be now fully supported.

Joined barlines for groups. Squared bracket. Left barline in empty scores

---

CHANGELOG.md
include/lomse_beam_engraver.h
include/lomse_gm_basic.h
include/lomse_lyrics_engraver.h
include/lomse_score_layouter.h
include/lomse_shape_tie.h
include/lomse_shape_tuplet.h
include/lomse_slur_engraver.h
include/lomse_system_layouter.h
src/graphic_model/engravers/lomse_beam_engraver.cpp
src/graphic_model/engravers/lomse_lyrics_engraver.cpp
src/graphic_model/engravers/lomse_slur_engraver.cpp
src/graphic_model/layouters/lomse_layouter.cpp
src/graphic_model/layouters/lomse_score_layouter.cpp
src/graphic_model/layouters/lomse_system_layouter.cpp
src/graphic_model/lomse_gm_basic.cpp
src/graphic_model/lomse_shape_beam.cpp
src/graphic_model/lomse_shape_brace_bracket.cpp
src/graphic_model/lomse_shape_line.cpp
src/graphic_model/lomse_shape_tie.cpp
src/graphic_model/lomse_shape_tuplet.cpp
src/tests/lomse_test_score_layouter.cpp

Currently, for deciding whether to include a system in current page or to place it in a new page, an estimated system height is used because the real height is not yet known. This PR changes the approach: first the system is engraved and once the real height is known the decision to place it in current page or to start a new one is taken.
Apart from changing the laying out algorithm, this PR fixes some engravers and some shapes so that a system can be relocated to a new page or to a new position without having to engrave it again in the new position.

Improve score layout algorithm to deal with systems with variable height

---

CHANGELOG.md
src/exporters/lomse_ldp_exporter.cpp
src/tests/lomse_test_command.cpp
src/tests/lomse_test_document.cpp
src/tests/lomse_test_document_layouter.cpp
src/tests/lomse_test_graphic_model.cpp
src/tests/lomse_test_ldp_analyser.cpp
src/tests/lomse_test_ldp_compiler.cpp
src/tests/lomse_test_ldp_exporter.cpp
src/tests/lomse_test_lmd_analyser.cpp
src/tests/lomse_test_lmd_compiler.cpp
src/tests/lomse_test_mxl_analyser.cpp
src/tests/lomse_test_presenter.cpp
src/tests/lomse_test_score_cursor.cpp
src/tests/lomse_test_score_layouter.cpp
src/tests/lomse_test_score_meter.cpp
src/tests/lomse_test_staffobjs_table.cpp
src/tests/lomse_test_system_cursor.cpp

LDP Exporter needed some improvements:
- First,  blank space in LDP exporter has been normalized. This simplifies automated tests and produces LDP code that is, visually, better.
- But the most important change has been to ensure that LDP exporter follows the same syntax rules than LDP Analyser, thus ensuring a round trip in LDP export-import.
- Some fixes in LDP exporter also added, for generating code for elements or options that were not taken into account.

LDP Exporter improvements

---

CHANGELOG.md
include/lomse_spacing_algorithm_gourlay.h
src/graphic_model/layouters/lomse_spacing_algorithm.cpp
src/graphic_model/layouters/lomse_spacing_algorithm_gourlay.cpp
src/tests/lomse_test_spacing_algorithm.cpp
test-scores/00142-clef-change-at-start.lms
test-scores/02042-text-attached.lms

Fixes spacing issues with non-standard scores with several consecutive clefs, detected in regression tests after changing the spacing algorithm.

Fix prolog spacing issues detected in regression tests

---

CHANGELOG.md
src/graphic_model/lomse_shapes.cpp
src/mvc/lomse_graphic_view.cpp

This PR fixes issue #73 and also implements method SimpleView::get_view_size() that was empty.
@juuk100 
In relation to your question about the image size, method view->get_view_size(&xWidth, &yHeight) will return the size for rendering the full score (all the pages). For k_simple_view it will return the size for rendering one page without borders. For other view types it will return the size for rendering all pages, including the margin between pages, and left and right view margins.
I've noticed that in your tests you are using k_view_simple. Take into account that SimpleView is just for rendering small scores that occupy a page at maximum. It assumes that the score has only a page and doesn't checks this, so behaviour can be wrong for scores having more than one page. I developed it …

Fixes #73: Highlight is not synced. when moving to next page

---

CHANGELOG.md
include/lomse_im_note.h
src/internal_model/lomse_im_note.cpp
src/parser/mxl/lomse_mxl_analyser.cpp
src/tests/lomse_test_mxl_analyser.cpp

It was a problem in MusicXML importer, with the &lt;alter&gt; element. The pitch for notes with accidentals was computed wrong. It is now fixed.

Fix #77: The score and sound do not match

---

CHANGELOG.md
include/lomse_internal_model.h
include/lomse_linker.h
src/document/lomse_command.cpp
src/exporters/lomse_ldp_exporter.cpp
src/internal_model/lomse_im_factory.cpp
src/internal_model/lomse_internal_model.cpp
src/parser/ldp/lomse_ldp_analyser.cpp
src/parser/lmd/lomse_lmd_analyser.cpp
src/parser/lomse_linker.cpp
src/parser/mxl/lomse_mxl_analyser.cpp
src/sound/lomse_midi_table.cpp
src/tests/lomse_test_ldp_analyser.cpp
src/tests/lomse_test_mxl_analyser.cpp

This PR fixes #82. Now all midi information is extracted from MusicXML files. But in playback, only channel and program are used. See #85

Fix #82. MusicXML importer: midi information in score-part is ignored

---

CHANGELOG.md
add-sources.cmake
include/lomse_internal_model.h
include/lomse_jumps_table.h
include/lomse_linker.h
src/exporters/lomse_ldp_exporter.cpp
src/exporters/lomse_lmd_exporter.cpp
src/internal_model/lomse_im_factory.cpp
src/internal_model/lomse_internal_model.cpp
src/internal_model/lomse_jumps_table.cpp
src/parser/ldp/lomse_ldp_analyser.cpp
src/parser/lmd/lomse_lmd_analyser.cpp
src/parser/lomse_linker.cpp
src/parser/lomse_model_builder.cpp
src/parser/mxl/lomse_mxl_analyser.cpp
src/sound/lomse_midi_table.cpp
src/tests/lomse_test_command.cpp
src/tests/lomse_test_document_cursor.cpp
src/tests/lomse_test_im_visitor.cpp
src/tests/lomse_test_jumps_table.cpp
src/tests/lomse_test_ldp_analyser.cpp
src/tests/lomse_test_model_builder.cpp
src/tests/lomse_test_mxl_analyser.cpp
src/tests/lomse_test_score_cursor.cpp

Instead of assigning MIDI channel 0 to any instrument without MIDI settings, now a different channel is assigned to each instrument. Also some changes for starting other pending fixes. The main changes are:
* ImoInstrument now supports many ImoSoundInfo nodes.
* Parsing an &lt;score-instrument&gt; element now generates a new ImoSoundInfo node.
* &lt;midi-instrument&gt; element is now required to match an id in &lt;score-instrument&gt; list
* ImoMidiInfo has been replaced by ImoSoundInfo. ImoMidiInfo removed.
* ImoSoundInfo initialization: changed for no channel, no port.
* ModelBuilder: Added class MidiAssigner to do midi mapping when no midi information in any instrument.
* Added class JumpsTable, for starting to deal with repetitions in playback.

Fixes #81: Default MIDI channel when no midi information in file

---

CHANGELOG.md
add-sources.cmake
include/lomse_coda_segno_engraver.h
include/lomse_gm_basic.h
include/lomse_internal_model.h
include/lomse_mxl_analyser.h
include/lomse_shape_base.h
include/lomse_shapes.h
src/graphic_model/engravers/lomse_coda_segno_engraver.cpp
src/graphic_model/layouters/lomse_score_layouter.cpp
src/graphic_model/layouters/lomse_spacing_algorithm_gourlay.cpp
src/graphic_model/lomse_gm_basic.cpp
src/internal_model/lomse_im_factory.cpp
src/internal_model/lomse_internal_model.cpp
src/parser/mxl/lomse_mxl_analyser.cpp
src/tests/lomse_test_mxl_analyser.cpp

With this PR Segno and Coda symbols are now imported from MusicXML files and properly rendered.
This PR is another step for fixing #79.

Import and render <coda>/<segno> repetition marks

---

CHANGELOG.md
include/lomse_box_system.h
include/lomse_events.h
include/lomse_gm_basic.h
include/lomse_graphic_view.h
include/lomse_interactor.h
include/lomse_score_player.h
src/graphic_model/layouters/lomse_score_layouter.cpp
src/graphic_model/lomse_box_score_page.cpp
src/graphic_model/lomse_gm_basic.cpp
src/mvc/lomse_graphic_view.cpp
src/mvc/lomse_interactor.cpp
src/sound/lomse_score_player.cpp

This PR fixes issue #88
When playing back an score it is necessary to ensure that current played notes are visible. Therefore, as the playback advances, the score should auto-scroll to maintain the viewport on the notes being played back.
The implemented solution defines a new Lomse event, *EventUpdateViewport*, that informs about the need to change the viewport and provides the coordinates for the new viewport origin. It is up to the user application to do it or not. This solution gives flexibility for changing/improving the auto-scroll algorithm without affecting user applications. And gives freedom to the user application to use the auto-scroll facility or to ignore the new events.
The implemented solution works as follows:
When the *ScorePlayer* object detects that the next note/rest …

Implement auto-scroll during playback

---

CHANGELOG.md
build-version.cmake
debian/changelog
docs/api/doxyfile
docs/api/mainpages/callbacks.h
docs/api/mainpages/code-license.h
docs/api/mainpages/coordinates-viewport.h
docs/api/mainpages/edit-overview.h
docs/api/mainpages/events.h
docs/api/mainpages/file-formats.h
docs/api/mainpages/introduction.h
docs/api/mainpages/library-license.h
docs/api/mainpages/overview.h
docs/api/mainpages/printing.h
docs/api/mainpages/render-overview.h
docs/api/mainpages/sound-generation.h
docs/api/mainpages/tasks.h
include/lomse_doorway.h
include/lomse_events.h
include/lomse_interactor.h
include/lomse_presenter.h
src/graphic_model/lomse_gm_basic.cpp
src/gui_controls/lomse_score_player_ctrl.cpp
src/module/lomse_events.cpp
src/module/lomse_injectors.cpp
src/mvc/lomse_interactor.cpp
src/sound/lomse_score_player.cpp
src/tests/lomse_test_score_player.cpp

This PR closes #111.
The documentation about events has been reviewed and improved.
Due to refactoring events code, some names have been changed and this results in backwards incompatible API changes. Due to this, library version number has been changed.

Refactor some events and improve documentation

---

include/lomse_events_dispatcher.h
include/lomse_internal_model.h
include/lomse_score_player.h
include/lomse_spacing_algorithm_gourlay.h
include/lomse_system_layouter.h
include/lomse_tasks.h
packages/minizip/ioapi.c
src/document/lomse_command.cpp
src/exporters/lomse_ldp_exporter.cpp
src/exporters/lomse_lmd_exporter.cpp
src/exporters/lomse_mnx_exporter.cpp
src/graphic_model/layouters/lomse_spacing_algorithm_gourlay.cpp

This fixes compilation errors on Windows. I'm using Visual Studio 2015 but the changes are not specific to that compiler version.
The following error occurs for many compilation units:
```
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\thr/xtimec.h(24): error C2872: 'xtime': ambiguous symbol (compiling source file src\graphic_model\lomse_caret.cpp)
```
It happens due to simultaneous `using boost` and `using std`.
The fix was to not `using boost`. That was easy because the boost symbols are used with full qualifiers throughout the lomse code, except one place where I added boost names prefixes.
Compilation fails at:
```C
void fill_fopen_filefunc (pzlib_filefunc_def)
zlib_filefunc_def* pzlib_filefunc_def;
{
...
```
with
```
>packages\minizip\ioapi.c(223): error C2065: …
```

Fixed compilation errors on Windows

---

src/exporters/lomse_ldp_exporter.cpp
src/graphic_model/engravers/lomse_instrument_engraver.cpp
src/graphic_model/layouters/lomse_score_layouter.cpp
src/graphic_model/layouters/lomse_score_meter.cpp
src/graphic_model/layouters/lomse_spacing_algorithm.cpp
src/graphic_model/layouters/lomse_spacing_algorithm_gourlay.cpp
src/graphic_model/layouters/lomse_staffobjs_cursor.cpp
src/graphic_model/layouters/lomse_table_layouter.cpp
src/parser/lomse_autoclef.cpp
src/sound/lomse_midi_table.cpp

This is a fix to #125:
1) Using resize() instead of reserve() when need to access elements afterwards.
2) Removed unnecessary resize() before assign().

#125: Fixed vector resizing

---

examples/example_1_win32.cpp
src/graphic_model/lomse_overlays_generator.cpp

This is a follow up to #97. The PR consists of two commits:
1. one to allow negative stride;
2. a fix by @jellyr to windows example to use positive stride.
Any one of these commits fixes the issue with Windows example. Applied together they work too as well.
Tested on Windows 10 and XP.

Allow negative stride and fix Windows example

---

include/lomse_basic.h
include/lomse_document.h
include/lomse_document_cursor.h
include/lomse_events.h
include/lomse_events_dispatcher.h
include/lomse_graphic_view.h
include/lomse_image.h
include/lomse_interactor.h
include/lomse_ldp_elements.h
include/lomse_presenter.h
include/lomse_selections.h
include/lomse_visual_effect.h
src/document/lomse_document_cursor.cpp
src/graphic_model/layouters/lomse_right_aligner.cpp
src/graphic_model/lomse_caret_positioner.cpp

This is a follow-up to #131.
`boost::shared_ptr` has been replaced with `std::shared_ptr`. For most systems this is rather a cosmetic change because `std::shared_ptr` was already used via `ifdef` in `lomse_basic.h`:
```C++
//if it is a C++11 compliant compiler use std shared_ptr, else use boost shared_ptr
#if __cplusplus > 199711L
#include <memory>
#define SharedPtr std::shared_ptr
#else
#include <boost/shared_ptr.hpp>
#define SharedPtr boost::shared_ptr
#endif
```
Visual C++ however was still using boost because Visual C++ defines `__cplusplus ` to `199711L` (although it supports most from C++11, C++14 and C++17).
With this PR Visual C++ starts using `std::shared_ptr` too, like other compilers.

Always use std::shared_ptr

---

packages/minizip/ioapi.c

Minizip code uses `ftello64`, `fseeko64`, `fopen64`. MacOS doesn't have them and compilation fails.
Clang produces warnings during compilation:
```
Implicit declaration of function 'fopen64' is invalid in C99
Implicit declaration of function 'ftello64' is invalid in C99
Implicit declaration of function 'fseeko64' is invalid in C99
```
and errors during linking:
```
Undefined symbols for architecture x86_64:
"_fopen64", referenced from:
_fopen64_file_func in ioapi.o
"_fseeko64", referenced from:
_fseek64_file_func in ioapi.o
"_ftello64", referenced from:
_ftell64_file_func in ioapi.o
```
As suggested on stackoverflow (also related to minizip) a solution is to define the symbols as:
```C++
#ifdef __APPLE__
#define ftello64 ftello
#define fseeko64 fseeko
#define fopen64 fopen
#endif
```
That …

Fixed compilation error in minizip unit on macOS

---

src/graphic_model/engravers/lomse_chord_engraver.cpp

During testing of example [musicxml-files](https://www.musicxml.com/music-in-musicxml/example-set/) encountered program crashes on most of the files.
The issue has been localized to an iterator incremented two times in a row without bounds check.
After the fix 17 from 18 files are read (and displayed) without crash. One file still causes a crash but I wasn't able to fix this. In a case you want to fix this yourself - this is file "ActorPreludeSample.musicxml", which is the biggest one (1 MB) in the set.

Fixed crash in chord engraver layout_accidentals

---

.travis.yml

Currently test failures do not cause Travis builds to fail.
Take a look at [this Travis build execution](https://travis-ci.org/hugbug/lomse/builds/366269445#L1186). The build is marked as **passed** although one test has failed:
```
$ ./bin/testlib
Lomse version 0.23.0+aa5b271. Library tests runner.
Lomse build date: 13-Apr-2018 19:41:10
Path for tests scores: '/home/travis/build/hugbug/lomse/test-scores/'
Running all tests
/home/travis/build/hugbug/lomse/src/tests/lomse_test_ldp_analyser.cpp:8182: error: Failure in Analyser_Font_SizeError: errormsg.str() == expected.str()
FAILURE: 1 out of 1577 tests failed (1 failures).
Test time: 9.75 seconds.
Done. Your build exited with 0.
```
Tests failed yet the build exited with 0. This is because the tests are executed in `after_script` section, …

Travis build should fail on test failure

---

src/parser/ldp/lomse_ldp_analyser.cpp
src/parser/lmd/lomse_lmd_analyser.cpp
src/parser/mxl/lomse_mxl_analyser.cpp

This PR fixes:
>All unit tests error messages such as "Line 0. Invalid size '10pt'. Replaced by '12'." are originated in lomse_ldp_analyser.cpp, line 361, method float get_font_size_value(). I do not understand why. Received parameter should be something as "10pt".
It attempts to read from `istream` a text such as "10pt" whereas the intention was to read the text with stripped suffix such as "10".
It seems libstdc++ (used on Linux) reads until the first non-digit character and succeed (and therefore the bug went unnoticed). With libc++ (clang) any non-digit character causes reading failure. From my understanding of description of `operator >>` the clang's behaviour is the correct one.

Fixed test failures for invalid font size

---

CMakeLists.txt
lomse_config.h.cmake
src/tests/lomse_the_test_runner.cpp

On my Windows machine CMake fails to generate proper project file (it prints something about not being able to find boost libraries although I pass all necessary paths). Still I was able to manually add all tests to Visual Studio project file. Now I can run the tests.
Similar to my Mac machine some tests fail. If a test fails due to memory access error the Windows program can't deal with that and terminates completely (on Mac the program manages to survive, prints a message about unhandled exception and goes on to next test).
Unfortunately when the program terminates it doesn't print the name of the test it was running. Hence the first change to test runner: when running `testlib -v` the test runner prints names of tests before executing them. If a test fails the last printed line is the …

Extended parametrisation of test runner

---

src/tests/lomse_test_ldp_analyser.cpp
src/tests/lomse_test_lmd_analyser.cpp

In the following example:
```C++
TEST_FIXTURE(LdpAnalyserTestFixture, Dynamic_GeneratesRequest)
{
void* p1 = this;
void* p2 = static_cast<LdpAnalyserTestFixture*>(this);
```
In **clang** and **GCC** `p1 == p2` but not in **MSVC**, at least not for Fixture classes.
Therefore storing `this` in `set_request_callback` for the class inherited from `LdpAnalyserTestFixture*` and then type casting it to `LdpAnalyserTestFixture*` in `wrapper_lomse_request` causes access into wrong memory:
```
static void wrapper_lomse_request(void* pThis, Request* pRequest)
{
static_cast<LdpAnalyserTestFixture*>(pThis)->on_lomse_request(pRequest);
```
This PR fixes the issue by passing to `set_request_callback` the object of the type needed in that callback (type-casted).

Fixed tests "Dynamic_GeneratesRequest" failing in MSVC

---

src/file_system/lomse_image_reader.cpp

I had a test failure:
```
Non-standard unknown exception (catch in ImageReader::load_image)
lomse_test_ldp_analyser.cpp(10204): Failure in LdpAnalyserTest / Image_Ok: errormsg.str() == expected.str()
```
Error-callback of pnglib was executed:
```C++
void error_callback (png_structp, png_const_charp)
{
LOMSE_LOG_ERROR("error reading png image");
throw "error reading png image";
}
```
The second parameter contained text "iCCP: known incorrect sRGB profile".
Tested with another png image and the test has passed.
It turned out the callback was executed as a warning, not as an error.
The callback was configured:
```C++
png_set_error_fn(pReadStruct, 0, error_callback, error_callback );
```
The last parameter is for warnings. The same function was used for both errors and warnings. The function …

Do not fail on png warnings

---

CMakeLists.txt
build-options.cmake
include/lomse_basic.h
include/lomse_caret.h
include/lomse_events_dispatcher.h
include/lomse_injectors.h
include/lomse_internal_model.h
include/lomse_score_player.h
src/graphic_model/layouters/lomse_spacing_algorithm_gourlay.cpp
src/graphic_model/lomse_caret.cpp
src/graphic_model/lomse_overlays_generator.cpp
src/graphic_model/lomse_shape_volta_bracket.cpp
src/module/lomse_events_dispatcher.cpp
src/module/lomse_injectors.cpp
src/render/lomse_font_storage.cpp
src/sound/lomse_score_player.cpp
src/tests/lomse_test_score_player.cpp

In this PR we replace `boost::thread` with `std::thread`. That was the last module holding us with boost and therefore the CMake config was adjusted and dependency from boost there was removed.
Although partially explained in #131 for the sake of completeness here full description of changes which were made:
- `boost::thread`, `boost::mutex`, etc. replaced with their analogues from `std`;
- `ScorePlayer` used `timed_join` and `interrupt` which don't exist in standard library. `timed_join` was replaced with `join`. I do not consider this to be a big issue because:
* ScorePlayer already implements a proper signaling for interruption;
* external thread termination is dangerous anyway and should be avoided;
- `boost::asio` has no replacement. Since `LOMSE_USE_BOOST_ASIO` was an experimental …

 Replaced boost::thread with std::thread

---

CMakeLists.txt
add-sources.cmake
build-options.cmake
include/lomse_image_reader.h
liblomse.pc.cmake
lomse_config.h.cmake
src/file_system/lomse_file_system.cpp
src/file_system/lomse_image_reader.cpp
src/file_system/lomse_zip_stream.cpp
src/parser/lmd/lomse_lmd_compiler.cpp
src/parser/mnx/lomse_mnx_compiler.cpp
src/parser/mxl/lomse_mxl_compiler.cpp
src/tests/lomse_test_document.cpp
src/tests/lomse_test_image_reader.cpp
src/tests/lomse_test_ldp_analyser.cpp
src/tests/lomse_test_zip_stream.cpp

As previously discussed in #131 this PR implements the possibility to build Lomse without explicit dependency from zlib and pnglib.
**Note:** Freetype may still require zlib but that's regulated outside of Lomse build process. In particular on Windows official builds of Freetype don't require separate zlib (Freetype.dll probably has zlib statically integrated).
By default zlib and pnglib are used in Lomse like before and all features are enabled. To build without pnglib and/or zlib there are two CMake options (both `ON` by default):
- LOMSE_ENABLE_COMPRESSION;
- LOMSE_ENABLE_PNG.
In the following example we run CMake providing these two options:
```shell
cmake -G "Unix Makefiles" -DLOMSE_ENABLE_PNG=OFF -DLOMSE_ENABLE_COMPRESSION=OFF  ../lomse
```
**Note:** Pnglib can be deactivated …

Make dependencies from zlib and pnglib optional

---

.travis.yml

In this PR Travis config is extended to check Lomse with multiple compilers:
- **GCC 4.9** on Linux, default C++ library;
- **GCC 4.9** on Linux, debug C++ library (-D_GLIBCXX_DEBUG);
- **GCC 7** on Linux, default C++ library;
- **GCC 7** on Linux, debug C++ library (-D_GLIBCXX_DEBUG);
- **Clang 4.2** on macOS.
GCC 4.9 is the oldest GCC version supported by Lomse.
GCC 7 is the current stable version.
Clang is the default compiler on macOS and FreeBSD. Travis offers testing on macOS.
It's easy to add GCC 5 and GCC 6 to the test matrix. Not so easy but also possible to add Clang 3.6, 3.9, 4.0 and 5.0 on Linux.
However Travis limits the number of parallel jobs running. They don't define a hard number but in my experience only five jobs are running simultaneously. With five compiler …

Check with multiple compilers on Travis

---

include/lomse_score_player.h
src/sound/lomse_score_player.cpp

`ScorePlayer` has member `m_pThread` pointing to playback thread. It is initialised in `ScorePlayer::play_segment`:
```C++
m_pThread = LOMSE_NEW SoundThread(&ScorePlayer::thread_main, this,
```
and then used in `ScorePlayer::do_play`:
```C++
if (!m_pMidi || !m_pThread)
{
LOMSE_LOG_DEBUG(Logger::k_score_player, "<< Enter. No Midi or no thread. << Exit");
return;
}
```
Depending on how thread scheduler on OS works the new thread may become active before the first thread continues execution. In this case `m_pThread` may be not yet initialised when it is checked in `do_play`, causing do_play to immediately terminate.
This happens pretty often on Windows causing ScorePlayerTest to fail. In theory this may happen on other OSes too but I didn't see this test failed on Linux or macOS yet.
The …

ScorePlayer thread start synchronisation

---

CHANGELOG.md
docs/api/doxyfile
include/lomse_document.h
include/lomse_interactor.h
include/lomse_measures_table.h
include/lomse_midi_table.h
include/lomse_score_algorithms.h
include/lomse_score_player.h
scripts/build-api-docs.sh
src/document/lomse_document.cpp
src/internal_model/lomse_internal_model.cpp
src/internal_model/lomse_measures_table.cpp
src/internal_model/lomse_model_builder.cpp
src/internal_model/lomse_score_algorithms.cpp
src/mvc/lomse_interactor.cpp
src/sound/lomse_midi_table.cpp
src/sound/lomse_score_player.cpp
src/tests/lomse_test_midi_table.cpp
src/tests/lomse_test_model_builder.cpp
src/tests/lomse_test_score_algorithms.cpp

The interface for this new facility is the new method Interactor::define_beat(). This method defines the duration for one beat, for metronome and for methods that use measure/beat parameters to define a location. This value is shared by all scores contained in the document and can be changed at any time.
Changes while the score is being played back are ignored until playback finishes.
Default value when nothing specified is `k_beat_implied` meaning that Lomse will use the duration implied by the time signature; e.g. 4/4 = four beats, 6/8 = two beats, 3/8 = one beat, ...

Allow to define the duration of one beat

---

include/lomse_score_player.h
src/sound/lomse_score_player.cpp

During playback, when the time signature changes, it is necessary to adjust metronome clicks interval for maintaining notes duration equivalence, when nothing is specified in the score.

Fix metronome equivalence when TS change

---

CHANGELOG.md
include/lomse_interactor.h
include/lomse_score_algorithms.h
src/internal_model/lomse_score_algorithms.cpp
src/mvc/lomse_interactor.cpp
src/tests/lomse_test_score_algorithms.cpp

To avoid having to use beats and to have better control of the desired position, this PR implements methods for moving the tempo line visual effect and doing scroll using measure/location to specify the required position. These methods area analogous to those using measure/beat. But instead of beat, the displacement from start of measure, in lomse time units, is provided.
For instance, if current beat is a quarter note, moving the tempo line to measure 7 beat 2 will be the same than moving it to measure 7 location 64.

Methods using measure/location analogous to those using measure/beat

---

CHANGELOG.md
docs/api/mainpages/im-modification.h
docs/api/mainpages/internal-model.h
include/lomse_internal_model.h
include/lomse_ldp_analyser.h
include/lomse_mnx_analyser.h
include/lomse_mxl_analyser.h
src/internal_model/lomse_im_factory.cpp
src/internal_model/lomse_internal_model.cpp
src/parser/ldp/lomse_ldp_analyser.cpp
src/parser/mnx/lomse_mnx_analyser.cpp
src/parser/mxl/lomse_mxl_analyser.cpp
src/tests/lomse_test_ldp_analyser.cpp
src/tests/lomse_test_mnx_analyser.cpp
src/tests/lomse_test_mxl_analyser.cpp

Until now, the internal model didn't store information about measure attributes, such as the displayed measure number.
This PR introduces changes in the internal model for capturing attributes related to measures. All importers now parse and store this information. The API documentation has been updated.

Changes for dealing with measure properties in the internal model

---

include/lomse_document.h
include/lomse_document_layouter.h
include/lomse_internal_model.h
include/lomse_layouter.h
include/lomse_score_layouter.h
src/graphic_model/layouters/lomse_blocks_container_layouter.cpp
src/graphic_model/layouters/lomse_document_layouter.cpp
src/graphic_model/layouters/lomse_inlines_container_layouter.cpp
src/graphic_model/layouters/lomse_layouter.cpp
src/graphic_model/layouters/lomse_score_layouter.cpp
src/graphic_model/layouters/lomse_table_layouter.cpp
src/internal_model/lomse_internal_model.cpp

Fixes #226 
This PR implements auto-scaling when the paper height is too small.
A document content scaling factor has been defined. It is used for scaling the content of the document pages. Paper and paper margins are not affected, only the content inside the page margins. This is equivalent to scaling paper size in the opposite direction, e.g.:
make the score 10% smaller ==> make paper and page margings 10% greater
This scaling factor is now used in all methods for building the graphic model, whenever the paper size and page margins are retrieved.
Layouters have been modified for adjusting the scaling factor when the system height is greater than the page height. This can only occur in two cases:
1) malformed scores: paper too small for the number of instruments  and staff size, or
3) …

Implement auto-scaling when the paper height is too small

---

CMakeLists.txt

Should fix https://github.com/lenmus/lomse/issues/235#issuecomment-631240230 by not setting LOMSE_COMPILER_MSVC to true. Not tested in Windows10 neither directly nor with MinGW.

Improve detection of MSVC compiler

---

include/lomse_graphic_view.h
include/lomse_score_layouter.h
include/lomse_shape_barline.h
src/graphic_model/layouters/lomse_score_layouter.cpp
src/graphic_model/lomse_shape_barline.cpp
src/parser/ldp/lomse_ldp_analyser.cpp

This PR adds support in LDP for centering snippet scores, that is, small scores with just one system and taking less width than available paper width. This option is intended for examples embedded in eBooks.
Also this PR includes some fixes for typos in Views documentation, and a fix for barlines that were not properly drawn when requested to use a colour  instead of B&W.

Implement option to center snippet scores

---

add-sources.cmake
include/lomse_compressed_mxl_compiler.h
include/lomse_injectors.h
include/lomse_parser.h
include/lomse_zip_stream.h
include/private/lomse_document_p.h
src/document/lomse_document.cpp
src/file_system/lomse_zip_stream.cpp
src/module/lomse_injectors.cpp
src/mvc/lomse_presenter.cpp
src/parser/lomse_compiler.cpp
src/parser/mxl/lomse_compressed_mxl_compiler.cpp

Currently Lomse is able to read uncompressed MusicXML files but refuses to open the compressed (`.mxl`) MusicXML files. This pull request implements a `Compiler` subclass for reading `.mxl` format which uncompresses the root MusicXML file and passes its content to the usual compiler for MusicXML format. The implementation of reading `.mxl` format follows [this reference](https://www.musicxml.com/tutorial/compressed-mxl-files/). Of course all this works only if Lomse is built with compression support, although I am not sure whether it makes sense to fully exclude `.mxl` compiler and the relevant methods from Lomse build in case compression support is disabled.
In general I tried to follow architecture and coding style seen around in the Lomse library but could certainly miss something. …

Add support for reading compressed MusicXML files

---

add-sources.cmake
include/lomse_box_system.h
include/lomse_gm_basic.h
include/lomse_graphic_view.h
include/lomse_half_page_view.h
include/lomse_injectors.h
include/lomse_midi_table.h
src/graphic_model/layouters/lomse_document_layouter.cpp
src/graphic_model/layouters/lomse_inlines_container_layouter.cpp
src/graphic_model/lomse_box_score_page.cpp
src/module/lomse_injectors.cpp
src/mvc/lomse_graphic_view.cpp
src/mvc/lomse_half_page_view.cpp
src/mvc/lomse_interactor.cpp
src/sound/lomse_midi_table.cpp
src/tests/lomse_test_midi_table.cpp

Closes #247. This view has a double behaviour:
- In normal mode (no playback) it behaves as SinglePageView: a single page as high as necessary to contain all the score.
- When entered in playback mode, the bitmap to be rendered in the application window is split horizontally in two halves, originating two virtual vertical windows, one at top and the other at bottom. In the top window it is displayed the first score chunk and the second chunk is displayed in the bottom window. When playback enters in the bottom window the top window is updated with the third chunk. Next, when the playback enters again in the top window, the bottom window is updated with the next chunk, and so on.
- When playback is finished (because the end of the score is reached or because the app stops playback  -- but …

Implement HalfPageView

---

include/lomse_internal_model.h
src/internal_model/lomse_api_internal_model.cpp

The internal model API is changed to remove virtual inheritance (only when compiling for Windows)

Bypass for Microsoft compiler bug

---

packages/minizip/ioapi.c
packages/minizip/ioapi.h

This pull request contains changes that are necessary to compile Lomse library for Android. Similar to #135, it was necessary to replace `ftello64`, `fseeko64` and `fopen64` functions which are not present on Android. In addition to that, I have added a change to `ioapi.h` which disables using 64-bit flavors of these functions when building for Android. This was necessary to get compressed files support in Lomse working on Android versions earlier than Android 7 (API level 24) since those versions didn't have 64-bit `fseeko`/`ftello` functions. This change disables support of compressed files larger than 4GB on that platform, but it doesn't seem to be needed for musical file formats anyway.
A similar change has also been done in [another …

Enable compilation on Android

---

include/lomse_command.h
include/lomse_doorway.h
include/lomse_logger.h
include/lomse_score_layouter.h
src/document/lomse_command.cpp
src/graphic_model/layouters/lomse_score_layouter.cpp
src/graphic_model/layouters/lomse_spacing_algorithm_gourlay.cpp
src/module/lomse_doorway.cpp
src/module/lomse_logger.cpp
src/platform/lomse_linux.cpp
src/platform/lomse_other.cpp
src/platform/lomse_windows.cpp

This pull request is more intended for a discussion of the proposed changes, although it already implements a fully working solution at the moment.
The proposed change tries to enable applications to customize the way Lomse does its logging. Currently Lomse puts its logs to files at certain predefined paths which may be not suitable for all applications. An application may want to put logs to its application-specific directory, disable logging at all (like it has been done in https://github.com/hugbug/conpianist/issues/32) or redirect logs to another destination (standard output/error streams (`stdout`/`stderr`) or platform-specific logging systems like Android Logcat).
The proposal is to allow applications initialize logging system before creating `LomseDoorway` object by calling …

Make logger output destination customizable

---

include/lomse_midi_table.h
include/private/lomse_internal_model_p.h
src/exporters/lomse_ldp_exporter.cpp
src/graphic_model/layouters/lomse_score_layouter.cpp
src/graphic_model/layouters/lomse_spacing_algorithm_gourlay.cpp
src/internal_model/lomse_im_factory.cpp
src/internal_model/lomse_internal_model.cpp
src/internal_model/lomse_staffobjs_table.cpp
src/parser/mxl/lomse_mxl_analyser.cpp
src/sound/lomse_midi_table.cpp
src/tests/lomse_test_midi_table.cpp
src/tests/lomse_test_mxl_analyser.cpp
src/tests/lomse_test_staffobjs_table.cpp
test-scores/unit-tests/transpose/001-transpose.xml
test-scores/unit-tests/transpose/002-transpose-octave-change.xml

This PR adds support for transposing instruments:
- The internal model now includes transposition information
- MusicXML importer now processes `<transpose>` elements
- Transposition information is now taken into account to build sound model and for playback
closes #93

Support transpose in internal model, MusicXML, and playback.

---

.appveyor.yml
CMakeLists.txt

This PR tries to fix AppVeyor build which seems to be broken for a while in this repo.
The issue (possibly not the only one) seems to be that CMake build automatically tries to launch unit tests, but:
1. Path to the executable file seems to be determined incorrectly (this is something to be fixed separately though);
2. Correct libraries (at least `freetype.dll`) are not copied to the necessary location at that stage.
This makes build fail on `cmake --build .` execution stage, before AppVeyor build tries to copy the necessary libraries and launch the test executable.
This PR essentially restores `LOMSE_RUN_TESTS` option removed in cdc3a0fd171b58658ba2110f0b5b9bb5531d1f1b and turns it off in AppVeyor build to allow tests be launched as it is defined in `.appveyor.yml` configuration. I am …

Try to fix AppVeyor build

---

include/lomse_mxl_analyser.h
include/private/lomse_internal_model_p.h
src/graphic_model/layouters/lomse_staffobjs_cursor.cpp
src/parser/mxl/lomse_mxl_analyser.cpp

Fixes #266.
This fix allows octave shifts start (and end) with `ImoNoteRest` rather than only `ImoNote`, and modifies the relevant places in the code (MusicXML reading and octave shifts handling in `StaffObjsCursor`) correspondingly. After these changes octave shifts starting with rests seem to be loaded and rendered correctly. However, I am not sure whether allowing octave shifts start only with notes was intentional, and whether I could miss something else with my changes.

Fix a crash on reading MusicXML file with octave shift starting with a rest

---

src/internal_model/lomse_staffobjs_table.cpp
src/tests/lomse_test_staffobjs_table.cpp
test-scores/unit-tests/colstaffobjs/07-clef-change.lms

When a clef change after a barline Lomse renders the clef *after* the barline, preserving definition order:
This PR fixes this bug, and now it renders this correctly:

Fix clef change incorrectly laid out

---

include/lomse_volta_engraver.h
src/graphic_model/engravers/lomse_volta_engraver.cpp

This pull request corrects appearance of volta which happen to start at the first measure of a system.
The issue can be reproduced, for example, on a score from [`test-scores/unit-tests/repeats/04-repeat-barline-simple-volta.xml`](https://github.com/lenmus/lomse/blob/1f7b2235e8690f6a4c3de4cfe1cf0ff27d3a3373/test-scores/unit-tests/repeats/04-repeat-barline-simple-volta.xml). If you open this file with Lomse and set page width so that the second volta starts on a new system, the score is rendered as follows (note that number `2` and some part of a bracket are drawn after the end of the first system):
The reason of this issue seems to be that volta brackets are bound to barlines in the internal model, and the relevant start barline for a volta is actually located at the end of the previous …

Correct engraving of volta located at the start of a system

---

include/lomse_beam_engraver.h
include/lomse_engraver.h
include/lomse_octave_shift_engraver.h
include/lomse_score_layouter.h
include/lomse_slur_engraver.h
include/lomse_system_layouter.h
include/lomse_tie_engraver.h
include/lomse_tuplet_engraver.h
include/lomse_volta_engraver.h
include/lomse_wedge_engraver.h
src/graphic_model/engravers/lomse_beam_engraver.cpp
src/graphic_model/engravers/lomse_octave_shift_engraver.cpp
src/graphic_model/engravers/lomse_slur_engraver.cpp
src/graphic_model/engravers/lomse_tie_engraver.cpp
src/graphic_model/engravers/lomse_tuplet_engraver.cpp
src/graphic_model/engravers/lomse_volta_engraver.cpp
src/graphic_model/engravers/lomse_wedge_engraver.cpp
src/graphic_model/layouters/lomse_score_layouter.cpp
src/graphic_model/layouters/lomse_spacing_algorithm.cpp
src/graphic_model/layouters/lomse_system_layouter.cpp

This PR fixes #273. Also fixes the same problem in all current spanner RelObjs (wedges, volta brackets and octave shifts).
Method `create_intermediate_shape()` is protected in engravers. The public method that triggers its invocation is `create_first_or_intermediate_shape()`. For spanner RelObjs, the engraver invokes `create_intermediate_shape()` to create a shape for the whole system when the start point is in a previous sytem and the end point is in a later system.
The problem causing that method `create_first_or_intermediate_shape()` was not invoked for intermediate shapes was that pending objects lists `m_notFinishedRelObj` and `m_notFinishedLyrics` were declared as member variables in `SystemLayouter` and thus, they were erased after finishing engraving each system. Now its scope is …

Fix intermediate shapes not created for spanner RelObjs

---

include/lomse_wedge_engraver.h
src/graphic_model/engravers/lomse_volta_engraver.cpp
src/graphic_model/engravers/lomse_wedge_engraver.cpp
test-scores/dev-tests/spanners/octave-shift-02-start-at-end-of-system.xml

This PR fixes a similar issue to #272, but for wedges, when the wedge starts just before the last barline in a system. See, for instance, the two small segments at end of first system in this image (tests-scores/dev-tests/spanners/wedge-02-start-at-end-of-system.xml):
I have also checked in octave-shifts but there the issue is not present there because the octave-shift will be attached to a note. See, for instance, tests-scores/dev-tests/spanners/octave-shift-02-start-at-end-of-system.xml.
I have fixed the issue in wedges following the same approach that you did in volta brackets.
As to how to detect that we are at end of a system, in the case of a wedge it is a ImoDirection preceding a ImoBarline and, thus, detecting that the barline is the last on in the system is of no help. The …

Correct engraving of wedge when at end of system

---

include/lomse_mxl_analyser.h
include/private/lomse_internal_model_p.h
src/internal_model/lomse_internal_model.cpp
src/parser/mxl/lomse_mxl_analyser.cpp

Currently dynamics markings engraver assumes that dynamics is attached to a note or rest. MusicXML importer however attaches it to `ImoDirection` when reading it as a descendant of `<direction>` tag. This difference results in dynamics being not aligned with notes or rests which they belongs to, for example (with [`test-scores/50035-directions-take-no-space.xml`](https://github.com/lenmus/lomse/blob/fe7e7bc993c5b83a5fee5b8bf682d5ead21b6d9f/test-scores/50035-directions-take-no-space.xml))
With some real-world scores it may look even worse: some dynamics marks become crossing barlines and causing some wedges being pushed further down:
This commit makes MusicXML analyser attach dynamics markings to notes and rests instead of `ImoDirection`. I am not sure whether it has any implications on …

Attach dynamics markings to notes or rests on reading MusicXML files

---

src/exporters/lomse_ldp_exporter.cpp
src/internal_model/lomse_staffobjs_table.cpp
src/parser/mxl/lomse_mxl_analyser.cpp
src/tests/lomse_test_ldp_exporter.cpp
src/tests/lomse_test_staffobjs_table.cpp
test-scores/unit-tests/colstaffobjs/08-direction-after-ts-in-2nd-instr.xml

This PR fixes a couple of issues detected when importing a MusicXML file:
- Notes not taking visible space `<note print-spacing="no">` are no longer imported.
- Fix a rule for ordering StaffObjs.
- Cue notes are now imported, although for now they are displayed as normal notes.

Fix crash related to MusicXML importer

---

scripts/regression.sh
src/render/lomse_renderer.cpp

In `RendererFactory`, not all pix_formats return a valid renderer and this causes later a crash. To facilitate diagnosing this crashes, the program now logs an error message and throws.
Also, minor changes in `regression.sh` script, to remove no longer used code.

Throw when invalid pixel format

---

src/graphic_model/layouters/lomse_score_layouter.cpp
src/parser/mxl/lomse_mxl_analyser.cpp
src/sound/lomse_midi_table.cpp

Closes #252. With this PR cue notes are properly imported in MusicXML, and are correctly managed: are rendered in smaller size and are ignored in playback.

Add full support for cue notes

---

include/lomse_barline_engraver.h
include/lomse_box_slice.h
include/lomse_box_slice_instr.h
include/lomse_box_system.h
include/lomse_instrument_engraver.h
include/lomse_shape_barline.h
src/graphic_model/engravers/lomse_barline_engraver.cpp
src/graphic_model/engravers/lomse_instrument_engraver.cpp
src/graphic_model/layouters/lomse_score_layouter.cpp
src/graphic_model/layouters/lomse_system_layouter.cpp
src/graphic_model/lomse_box_slice.cpp
src/graphic_model/lomse_box_slice_instr.cpp
src/graphic_model/lomse_box_system.cpp
src/graphic_model/lomse_shape_barline.cpp

Currently Lomse draws dots of repeat barlines only on the first staff of the instrument, for example:
However repeat dots are commonly placed on each staff in multi-staff scores. This PR makes repeat dots appear on all staves, so the example shown above now looks like the following:
As repeat dots drawing is handled by a barline shape, this shape needs to know coordinates of all staves in its range, so most of the changes in this PR are about forwarding this information to barline shapes. The first commit here reverts b3c2f2b4c2d32040fad74b8f3efaa91a2175ad62 and instead ensures that vertical staff position shifts are reset when a new system's layout begins. This is needed to ensure that `InstrumentEngraver::get_top_line_of_staff()` (which definition is changed to take these shifts into …

Draw repeat barline dots on all staves

---

src/parser/mxl/lomse_mxl_analyser.cpp
src/tests/lomse_test_mxl_analyser.cpp

Similar to slurs (which are handled in #286), wedge end can be found before wedge start in a MusicXML file. The code responsible for reading wedges has a provision for this case so such wedges are already imported. However order of endpoints of such wedges is wrong which leads to a crash on an attempt to render such wedge. A minimal example of this case can be given by this file: 
[wedge.musicxml.zip](https://github.com/lenmus/lomse/files/6796796/wedge.musicxml.zip)
This pull request changes handling of wedges' endpoints in the same way as it has been done for slurs in #286, so order of wedge endpoints is corrected so that wedge stop always goes last. This allows to properly import and display such wedges.
This pull request though doesn't deal with the reason of the crash itself, so an …

MusicXML: fix wedge endpoints order if wedge end is found before wedge start

---

include/lomse_score_iterator.h
include/lomse_staffobjs_table.h
include/lomse_xml_parser.h
include/private/lomse_internal_model_p.h
src/internal_model/lomse_internal_model.cpp
src/score/lomse_score_iterator.cpp

This PR fixes [`-Wdeprecated-copy`](https://gcc.gnu.org/onlinedocs/gcc/C_002b_002b-Dialect-Options.html) warnings which appear when compiling Lomse with GCC 10. The reason of the warnings is that some classes contain declarations only for one of copy constructor or copy assignment operator, but the other declaration was missing (but actually used by the library's code). Therefore a compiler is forced to generate the missing constructor/operator itself but this is deprecated in such situation since C++11 and actually should not normally happen since this violates [the rule of three](https://en.wikipedia.org/wiki/Rule_of_three_(C%2B%2B_programming)). Therefore in order to avoid the warning (and potential issues related to this situation) copy constructor and copy assignment operator should …

Fix -Wdeprecated-copy compiler warnings from GCC

---

docs/api/doxyfile
include/lomse_model_builder.h
src/graphic_model/layouters/lomse_score_layouter.cpp

When the internal model has a malformed `ImoRelObj` (start and end not in music time order) Lomse will crash when trying to render it. These situations could occur, for instance, when importing a malformed MusicXML file with one or more spanners reversed. See comments in PR#296.
I've analysed the posibility of `ModelBuilder` trying to fix any malformed `ImoRelObj` but it is complex when more than two `ImoStaffObj` are involved (e.g., spanners with 'continue' intermediate points) as in these cases it is not possible to know exactly which is the correct order.
Therefore, instead of trying to fix the malformed `ImoRelObj` this PR just add checks to avoid crashes during rendition.
It also includes two unrelated non-important commits:
• The version number is increased in API documentation …

Avoid crashes with malformed files (spanners reversed)

---

include/lomse_bitmap_drawer.h
include/lomse_calligrapher.h
include/lomse_chord_engraver.h
include/lomse_drawer.h
include/lomse_engraving_options.h
include/lomse_glyphs.h
include/lomse_gm_basic.h
include/lomse_im_note.h
include/lomse_mxl_analyser.h
include/lomse_shape_base.h
include/lomse_shape_note.h
include/lomse_shapes.h
include/private/lomse_internal_model_p.h
src/graphic_model/engravers/lomse_chord_engraver.cpp
src/graphic_model/lomse_box_slice_instr.cpp
src/graphic_model/lomse_glyphs.cpp
src/graphic_model/lomse_gm_basic.cpp
src/graphic_model/lomse_shapes.cpp
src/internal_model/lomse_im_factory.cpp
src/internal_model/lomse_im_note.cpp
src/internal_model/lomse_internal_model.cpp
src/parser/mxl/lomse_mxl_analyser.cpp
src/render/lomse_bitmap_drawer.cpp
src/render/lomse_calligrapher.cpp
src/tests/lomse_test_staffobjs_table.cpp

This pull request contains a basic implementation of arpeggio in Lomse. This implementation is somewhat limited (which I have briefly described below) but it is still able to import an arpeggio attached to one chord and display it when rendering a score. Therefore it can be useful to handle arpeggio in the most common cases and is hopefully able to serve as a basis for further improvements.
Here are some examples of arpeggio rendering with the current version of this PR:
- [`32d-Arpeggio.xml`](https://github.com/cuthbertLab/musicxmlTestSuite/blob/main/xmlFiles/32d-Arpeggio.xml) from the [unofficial MusicXML test suite](https://github.com/cuthbertLab/musicxmlTestSuite) (non-arpeggiate is not implemented in this pull request):
- Arpeggio of different lengths:
- Arpeggio on cross-staff …

Add initial support for arpeggio

---

include/lomse_path_attributes.h
src/parser/mxl/lomse_mxl_analyser.cpp

Playback loop was detected in MozartTrio smaple and fixed in this PR. It was caused by just a missing `k_barline_double_repetition_alt` in method `BarlineMxlAnalizer::combine_barlines()` but I take the opportunity to add a couple of unimportant changes:
- refactor a method, for better understanding
- add comments to explain conversion between MusicXML and Lomse barlines
- add a TODO comment to remember the need to improve that piece of code

Fix playback loop due to bug in MusicXML importer

---

src/graphic_model/layouters/lomse_system_layouter.cpp

This pull request fixes a case when a middle spanner segment is shown on a wrong page. The issue can be illustrated, for example, with this score: [slur.musicxml.txt](https://github.com/lenmus/lomse/files/6949826/slur.musicxml.txt)
To reproduce the issue two conditions are necessary:
1. A slur spans for several systems (because page width is small or a slur is particularly long)
2. A system somewhere in the middle of the slur range is moved to another page.
If these conditions are met a slur segment which belongs to the first system on the second page is instead displayed on the first page: 
| Page 1  | Page 2 |
| ------------- | ------------- |
| ![before1](https://user-images.githubusercontent.com/6000747/128613993-98c37038-b959-42a3-b92f-dbb56238947b.png) | …

Fix middle spanner segments being displayed on a wrong page in some cases

---

src/parser/mxl/lomse_mxl_analyser.cpp
src/tests/lomse_test_mxl_analyser.cpp

When Lomse reads a mid-score `<attributes>` tags which contains some value for `<staves>` larger than 1, it may attempt to add extra staves to the existing instrument, which may lead to adding spurious staves or even to a crash. This may occur with the scores exported from MuseScore if they contain section breaks, for example:
- [lomse_attr_staves_crash.musicxml.txt](https://github.com/lenmus/lomse/files/6950064/lomse_attr_staves_crash.musicxml.txt) — crashes Lomse on engraving stage
(the original score in the MuseScore format: [lomse_attr_staves_crash.mscx.txt](https://github.com/lenmus/lomse/files/6950071/lomse_attr_staves_crash.mscx.txt))
- [lomse_attr_staves_no_crash.musicxml.txt](https://github.com/lenmus/lomse/files/6950065/lomse_attr_staves_no_crash.musicxml.txt) — doesn't crash …

MusicXML: fix adding spurious staves on reading mid-score <attributes> with <staves> tag

---

include/lomse_staffobjs_table.h
src/internal_model/lomse_staffobjs_table.cpp
src/tests/lomse_test_staffobjs_table.cpp
test-scores/unit-tests/arpeggios/301-arpeggiated-chord-up.xml
test-scores/unit-tests/arpeggios/302-arpeggiated-chord-down.xml

This PR fixes #304.
I had doubts about how to compute the delay between arpeggio notes, as this is something that, to me, depends on tempo, chord note type and perhaps other factors. For now, I have set the total delay (on set time difference between first and last arpeggiated notes) to be the shortest time of (0.7 * chord duration) and one sixteenth note. In the tests with a few scores the arpeggios sound acceptable. But ideas for improving this computation are always welcome.

Support arpeggiated chords in playback

---

src/parser/mxl/lomse_mxl_analyser.cpp
src/tests/lomse_test_mxl_analyser.cpp

If a left barline is explicitly defined in a MusicXML score in the first measure Lomse still tries to combine it with the non-existing previous barline and crashes (which can be reproduced with [this example score](https://github.com/lenmus/lomse/files/6964977/test-repeat-start.musicxml.txt)). This PR simply adds a null-pointer check to prevent a crash and adds a simple test on basic handling of left and right barlines combining.
Ideally though a start repeat barline should be rendered after key and time signatures, whether they appear together in the beginning of a score or not. This may require MusicXML importer to do some extra work to sort the relevant objects in the score's object columns table but this involves more changes and isn't necessary for preventing the crash itself so I …

Fix a crash on reading a MusicXML score with a start repeat barline in the first measure

---

src/parser/mxl/lomse_mxl_analyser.cpp

Test score: [let-ring.musicxml.txt](https://github.com/lenmus/lomse/files/6978280/let-ring.musicxml.txt)
This PR fixes a crash on reading `<tied>` element which has an unknown `type` attribute value. Lomse prints a warning about the unknown attribute and warns that the tie would be ignored but actually a crash happens due to a missing null pointer check. Other similar element analyzers (at least those for slurs, wedges and octave shifts) already have similar checks in place and thus should not be affected by the issues of this type.
In the test file the unknown attribute value is `let-ring` which has been added in the 3.1 version of MusicXML, according to [the changelog](https://www.w3.org/2021/06/musicxml40/version-history/31). However it could possibly be some invalid value so this …

MusicXML: fix a crash on reading <tied> element with unknown type

---

include/lomse_engraver.h
include/lomse_gm_basic.h
include/lomse_wedge_engraver.h
src/graphic_model/engravers/lomse_engraver.cpp
src/graphic_model/engravers/lomse_wedge_engraver.cpp
src/graphic_model/lomse_gm_basic.cpp

This pull request provides a proof-of-concept implementation of a horizontal alignment of an object attached to an `ImoDirection` to staff object shapes by finding them in the graphical model, like discussed in #309.
It turns out that note and rest shapes currently belong to a `GmoBoxSliceStaff` box which maintain a list of their child shapes in engraving order. As staff objects seem to be engraved ordered by time, shapes in the `GmoBoxSliceStaff`'s list are also sorted by the time of the corresponding internal model objects. They are not however sorted by their `x` coordinates, and in order to obtain the leftmost note at a certain position one has to check all the notes in the current time position. Also the same list contains shapes for auxiliary and relation objects which are already …

Add a minimal implementation of StaffObjShapeCursor, improve wedge horizontal positioning

---

include/lomse_system_layouter.h
src/graphic_model/engravers/lomse_beam_engraver.cpp
src/graphic_model/layouters/lomse_system_layouter.cpp

This PR fixes another case of a crash with invisible notes (see also #311). If a beam includes invisible notes or fully consists of invisible notes then a crash happens because the engraver assumes that a beam always contains at least one visible note. This PR makes the engraver skip invisible staff objects passed to it and explicitly check that there are visible notes which can be used to engrave the beam. `m_numNotes` counter is reset later by the beam engraving algorithm so it should be fine to reuse it for this purpose.
Also this PR includes changes to properly delete the engraver if the last shape it produces is `nullptr`. Actually it would probably be even better if the `EngraverMap` would be responsible for deleting the engravers stored in it but this is probably something that …

Fix a crash on engraving a beam including invisible notes

---

include/lomse_tuplet_engraver.h
src/graphic_model/engravers/lomse_tuplet_engraver.cpp
src/graphic_model/lomse_shape_tuplet.cpp

Invisible notes are quite often found in digital score formats to achieve certain playback effects. Lomse correctly imports `print-object` attribute of such notes and creates invisible shapes in place of them but this doesn't play well with engraving some relation objects which happen to include such invisible notes. Therefore I have encountered a number of crashes on engraving scores which include invisible notes.
This pull requests fixes a crash in case an invisible note is a start or end note in a tuplet (a small example score: [lomse_tuplet_invisible_note_crash.musicxml.txt](https://github.com/lenmus/lomse/files/7027305/lomse_tuplet_invisible_note_crash.musicxml.txt)). In this case it is enough just to rearrange a bit a logic of the tuplet engraver to explicitly check all assumptions …

Fix a crash when a tuplet starts or ends with an invisible note

---

src/graphic_model/layouters/lomse_system_layouter.cpp

In order to ensure that different objects are engraved in the expected order Lomse makes several passes across the system's list of pending objects and engraves object of one type in each pass. However this doesn't work for objects that are not finished in the current system as those are engraved after engraving all objects that are finished in the current system. This leads to an inconsistent engraving order if unfinished relation objects are involved, for example (note that the order for a wedge and an octave shift is inverted when the octave shift spans for two systems):
This pull request moves engraving of non-finished relation objects to the same loop that does engraving of other objects which makes the engraving order more consistent between those objects:
(test file: …

Ensure that non-finished relation objects are engraved in the correct order

---

src/graphic_model/engravers/lomse_chord_engraver.cpp
src/graphic_model/engravers/lomse_note_engraver.cpp
src/internal_model/lomse_im_note.cpp

This PR fixes a crash which occurs with [this score](https://musescore.com/openscore/scores/5421848) for Beethoven's Moonlight Sonata. The part which produces this crash can be reduced down to this example score ([lomse_beaming_crash2.musicxml.txt](https://github.com/lenmus/lomse/files/7073131/lomse_beaming_crash2.musicxml.txt)):
In this score there is a beam which connects both chords and single notes and which is set up so that stem directions are different. The same beam with no chords does not produce a crash.
Stem directions for beams with chords are computed before engraving the beam by a special `BeamedChordHelper`, and the beam engraver does not compute stem directions by itself in this case. However when setting the `m_fDoubleStemmed` flag directions are taken [from the …

Fix a crash on engraving a double-stemmed beam with a chord and multiple notes

---

include/lomse_shape_base.h
src/graphic_model/engravers/lomse_chord_engraver.cpp
src/graphic_model/lomse_shape_base.cpp
src/tests/lomse_test_shapes.cpp

Notes in different voices that sound at the same time are vertically aligned in the score. These alignment lines are sometimes named ‘_beatlines_’ in academic literature but, in Lomse, for historical reasons, they are named ‘_anchor_’ lines.
This PR fixes the computation of anchor lines for chords, that caused alignment problems, e.g. test score 00623:
Current:
After this PR:
In addition, this PR removes methods `lock()` and `unlock()` in `GmoShapeComposite` an the related variable, as they are not used and are not needed.

Fix anchor line for chords

---

add-sources.cmake
include/lomse_aux_shapes_aligner.h
include/lomse_dynamics_mark_engraver.h
include/lomse_engraver.h
include/lomse_engraving_options.h
include/lomse_gm_basic.h
include/lomse_shape_wedge.h
include/lomse_shapes.h
include/lomse_system_layouter.h
include/lomse_vertical_profile.h
include/lomse_wedge_engraver.h
src/graphic_model/engravers/lomse_dynamics_mark_engraver.cpp
src/graphic_model/engravers/lomse_volta_engraver.cpp
src/graphic_model/engravers/lomse_wedge_engraver.cpp
src/graphic_model/layouters/lomse_aux_shapes_aligner.cpp
src/graphic_model/layouters/lomse_score_layouter.cpp
src/graphic_model/layouters/lomse_system_layouter.cpp
src/graphic_model/layouters/lomse_vertical_profile.cpp
src/graphic_model/lomse_shape_wedge.cpp

This pull request implements a mechanism to align auxiliary object with respect to each other, both horizontally and vertically. The implementation proposed here involves an introduction of a "horizontal layer" concept which basically means a set of objects which should be aligned with respect to each other if they are placed close enough. This concept is implemented by the `HorizontalLayer` and related classes, also the engraving order table was restructured to include the information about horizontal layers. There is one layer per placement per staff for each system (that is, shapes placed below and above staff are aligned separately). The information on shape placement doesn't seem to be readily available at the `SystemLayouter` level, so it is currently a responsibility of engravers …

Implement relative alignment of auxiliary objects, align voltas and hairpin-dynamic sequences

---

include/lomse_box_slice.h
include/lomse_box_system.h
include/lomse_engraving_options.h
include/lomse_gm_basic.h
include/lomse_score_layouter.h
include/lomse_system_layouter.h
src/graphic_model/layouters/lomse_score_layouter.cpp
src/graphic_model/layouters/lomse_system_layouter.cpp
src/graphic_model/lomse_box_slice.cpp
src/graphic_model/lomse_box_slice_instr.cpp
src/graphic_model/lomse_box_system.cpp

This PR improves vertical spacing between systems by enforcing a minimal distance between them. In current Lomse code this is not checked and the distance can be minimal or even systems can overlap. For instance, in current rendition of score
[MahlFaGe4Sample.musicxml.txt](https://github.com/lenmus/lomse/files/7186909/MahlFaGe4Sample.musicxml.txt) , in third system the wedges are touching previous system:
The following image displays the result, after applying this PR:
This PR does not increment systems distance in other cases, it only ensures that a minimal distance always exists. It also includes the following related changes:
- Information about free space at top and bottom of a system is now available in its `GmoBoxSystem` object, as it is required for checking the space between two …

Enforce a minimum distance between systems

---

include/lomse_engraving_options.h
include/lomse_key_engraver.h
src/graphic_model/engravers/lomse_key_engraver.cpp
src/graphic_model/layouters/lomse_score_layouter.cpp
src/graphic_model/layouters/lomse_spacing_algorithm.cpp

Currently Lomse doesn't display anything on a key change if the new key doesn't have any accidentals. This makes it impossible for a performer to figure out that a key change has happened (example score: [key-change-naturals.musicxml.txt](https://github.com/lenmus/lomse/files/7192164/key-change-naturals.musicxml.txt)):
In such cases naturals are commonly displayed to inform a performer about a key change. This PR implements this way of displaying such key changes:
Some extra spacing between naturals was also required to avoid naturals in a key signature being visually glued together, so that was also added to the key engraver.

Display naturals on a key change to Cmaj/Amin

---

include/lomse_document.h
include/lomse_mxl_analyser.h
include/private/lomse_internal_model_p.h
src/document/lomse_document.cpp
src/graphic_model/layouters/lomse_document_layouter.cpp
src/graphic_model/layouters/lomse_score_layouter.cpp
src/internal_model/lomse_internal_model.cpp
src/parser/ldp/lomse_ldp_analyser.cpp
src/parser/lmd/lomse_lmd_analyser.cpp
src/parser/lomse_linker.cpp
src/parser/mxl/lomse_mxl_analyser.cpp
src/tests/lomse_test_document_layouter.cpp
src/tests/lomse_test_internal_model.cpp
src/tests/lomse_test_ldp_analyser.cpp
src/tests/lomse_test_mxl_analyser.cpp

This PR imports the `<defaults>` element, with the exception of the `<concert-score>` element, useless for now, and the `<appearance>` values, also useless for now and because importing them will require to make engraving options not constant and this is not an urgent change.
The main achievements with this PR are:
- Page size and margins are now imported and taken into account. 
- System and staves distance and margins are also imported and taken into account. But, for distances (not for margins), the imported values could be overridden by the layout algorithm if more space was required.
- Font for words is now imported and used for texts.
- Font for lyrics and language for lyrics is now imported and used for lyric lines.
- Font for music is also imported but it is useless as Lomse will, …

MusicXML: Import <defaults> element

---

src/graphic_model/engravers/lomse_tie_engraver.cpp

Steps to reproduce the crash:
1) Load this score: [tie-next-system-crash.musicxml.txt](https://github.com/lenmus/lomse/files/7318100/tie-next-system-crash.musicxml.txt)
2) Reduce page width so that the notes connected by the tie appear in different systems.
Result: crash.
The issue was introduced by [this change](https://github.com/lenmus/lomse/commit/8f83729ba24673ec2c28d6b5963ca7116490bb47#diff-284f1bfd13108b71e89b9901509fa7cec19e4aaf7a928084a7587fe18698a0e0) in #324. With that change the tie engraver may try to take the second note's stem into account when deciding the tie placement. However if the end note appears on the next system an information about the end note's shape is not yet available to the engraver by the time it needs to create its first shape, so `m_pEndNoteShape` is a …

Fix a crash on engraving a tie if its end note is on the next system

---

include/lomse_score_player.h
src/sound/lomse_score_player.cpp

- Count-off created incorrect number of count-off pulses. Now always two pulses before the first beat with notes.
- In metronome, the first measure beat was not correctly detected when anacrusis start and thus, first beat sound was use for an incorrect beat.

Fix two bugs when playback with metronome and count-off

---

include/lomse_shape_note.h
src/graphic_model/engravers/lomse_chord_engraver.cpp
src/graphic_model/lomse_shape_note.cpp

This PR fixes a crash which happens on engraving this test score: [noterest-collision-fixer-crash.musicxml.txt](https://github.com/lenmus/lomse/files/7534155/noterest-collision-fixer-crash.musicxml.txt)
The crash happens at [this line](https://github.com/lenmus/lomse/blob/ca924db18798258d1d3b1e61cb2a4c23c1997442/src/graphic_model/layouters/lomse_noterests_collisions_fixer.cpp#L295) because the collision fixer tries to access the pointer to the chord's base note which is null in this case. This happens because this pointer is set only for some notes in a chord (which are marked as "start", "link" or "flag" notes) and for some notes this pointer may be left unassigned. The proposed fix is to explicitly set the pointer to the base note for all notes in a chord so that the collision fixer or …

Fix a crash on fixing a chord-rest collision due to a missing pointer to the chord's base note

---

src/graphic_model/engravers/lomse_chord_engraver.cpp

Using [test-score.musicxml.txt](https://github.com/lenmus/lomse/files/7581217/test-score.musicxml.txt)  when going to engrave the chord in second instrument, chord engraver looks for the applicable clef but, incorrectly, finds the clef change in instrument 1 because the method does not check for the clef instrument, and tries to assign the clef to the second staff of instrument 2 that do not exist, causing the crash.

Fix bug in chord engraver that causes a crash

---

include/lomse_chord_engraver.h
include/lomse_im_note.h
include/lomse_mnx_analyser.h
include/private/lomse_internal_model_p.h
src/exporters/lomse_ldp_exporter.cpp
src/graphic_model/engravers/lomse_chord_engraver.cpp
src/graphic_model/engravers/lomse_instrument_engraver.cpp
src/internal_model/lomse_api_internal_model.cpp
src/internal_model/lomse_im_factory.cpp
src/internal_model/lomse_internal_model.cpp
src/parser/lmd/lomse_lmd_analyser.cpp
src/parser/lomse_linker.cpp
src/parser/mnx/lomse_mnx_analyser.cpp
src/parser/mxl/lomse_mxl_analyser.cpp
src/tests/lomse_test_internal_model.cpp
src/tests/lomse_test_ldp_analyser.cpp
src/tests/lomse_test_mnx_analyser.cpp
src/tests/lomse_test_mxl_analyser.cpp
src/tests/lomse_test_staffobjs_table.cpp
src/tests/lomse_test_text_engraver.cpp

This PR reviews the internal model, in preparation for comming changes to support MNX. This PR mainly, modifies the implementation of AttObj objects to avoid using variant types, and do some refactoring.
**Changes**
- Implementation of AttrObj changed to avoid using variant types and to minimize memory usage.
- Created class AttrList for managing a simple list of AttrObj objects.
- Some refactoring in internal model objects:
- Removed ImoTextInfo objects that were used as member variables in other ImoObj objects, and replaced by TypeTextInfo struct.
- Default copy and move constructors forced to be deleted for most ImoObj objects. Not possible to remove yet from all ImoObj objects due to Dto and Info objects that need to be reviewed.
**Other changes**
- Memory leaks checked with Valgrind …

Changes in IM (redesing AttObj and ImoTextInfo), memory leaks and fixes

---

include/lomse_lyric_engraver.h
src/graphic_model/engravers/lomse_lyric_engraver.cpp
src/graphic_model/layouters/lomse_system_layouter.cpp

An `std::vector` was cleared and later was accesed. This has been fixed.

Fix critical bug that could cause crashes when the score has lyrics

---

src/graphic_model/lomse_shape_brace_bracket.cpp

At very high magnification the brace had too straight segments and some bumps. This has been fixed.

Fix vertices for braces

---

add-sources.cmake
docs/api/mainpages/render-overview.h
examples/svg/svg-minimal.cpp
include/lomse_checkbox_ctrl.h
include/lomse_drawer.h
include/lomse_graphic_view.h
include/lomse_interactor.h
include/lomse_shape_brace_bracket.h
include/lomse_shape_tie.h
include/lomse_shapes.h
include/lomse_svg_drawer.h
include/lomse_vertex_source.h
src/graphic_model/lomse_fragment_mark.cpp
src/graphic_model/lomse_graphical_model.cpp
src/graphic_model/lomse_shape_text.cpp
src/graphic_model/lomse_shape_tie.cpp
src/graphic_model/lomse_shapes.cpp
src/mvc/lomse_graphic_view.cpp
src/mvc/lomse_interactor.cpp
src/render/lomse_bitmap_drawer.cpp
src/render/lomse_svg_drawer.cpp

This PR starts adding support for rendering documents as a stream of SVG commands (as text, in HTML format). The new SVG rendering facilities are independent of the existing bitmap related methods and both can be used simultaneously.
**Limitations**
- For now there are neither IDs nor classes in SVG elements. Therefore, the SVG code for notes, rests and other music notation elements can not be identified, styled and manipulated by the user application. I expect to add all these in coming PRs.
- For now the only formatting option for SVG output is to add a line break after each SVG element. Default value is `false` (do not add new lines) for maximum compactness of generated code.
- The SVG rendition does not include any Lomse visual effects (tempo line, cursor, markers, etc.) as all them …

Render scores in SVG format

---

CMakeLists.txt
add-sources.cmake
include/lomse_doorway.h
include/lomse_events_dispatcher.h
include/lomse_injectors.h
include/lomse_instrument_engraver.h
include/lomse_ldp_elements.h
include/lomse_score_player.h
include/lomse_score_player_ctrl.h
include/lomse_svg_drawer.h
include/private/lomse_internal_model_p.h
lomse_config.h.cmake
scripts/build-lomse.sh
src/graphic_model/engravers/lomse_engrouters.cpp
src/graphic_model/engravers/lomse_instrument_engraver.cpp
src/graphic_model/layouters/lomse_layouter.cpp
src/gui_controls/lomse_score_player_ctrl.cpp
src/internal_model/lomse_im_factory.cpp
src/internal_model/lomse_internal_model.cpp
src/module/lomse_doorway.cpp
src/module/lomse_events_dispatcher.cpp
src/module/lomse_injectors.cpp
src/parser/ldp/lomse_ldp_analyser.cpp
src/parser/lmd/lomse_lmd_analyser.cpp
src/render/lomse_font_freetype.cpp
src/sound/lomse_score_player.cpp
src/tests/lomse_test_ldp_analyser.cpp
src/tests/lomse_test_lmd_analyser.cpp
src/tests/lomse_test_score_player.cpp

This PR adds additional options for building:
- Option `LOMSE_USING_EMSCRIPTEN` (Default: `OFF`) is oriented to build JavaScript bindings using the `Emscripten SDK`. This new option is used to inform cmake script that it is being run with Emscripten tools. When setting this, all other settings, such as `LOMSE_BUILD_SHARED_LIB`, `LOMSE_BUILD_TESTS`, `LOMSE_ENABLE_COMPRESSION`, etc. are ignored and the cmake script will instead use the pre-defined settings required for JavaScript bindings.
- Option `LOMSE_ENABLE_FONTCONFIG` (Default value: `ON`) is only meaningful for Linux systems and is used to control the dependency from the ‘fontconfig’ library. By setting this to `OFF` the dependency from 'fontconfig' is removed and Lomse will use only the fonts available in the path provided by the …

Add more options for customizing Lomse builds

---

CMakeLists.txt
add-group-folders.cmake
include/lomse_basic.h
include/lomse_box_slice.h
include/lomse_box_slice_instr.h
include/lomse_box_system.h
include/lomse_gm_measures_table.h
include/lomse_graphical_model.h
include/lomse_interactor.h
include/lomse_time.h
include/lomse_timegrid_table.h
include/lomse_vertical_profile.h
include/private/lomse_internal_model_p.h
src/file_system/lomse_image_reader.cpp
src/graphic_model/engravers/lomse_beam_engraver.cpp
src/graphic_model/engravers/lomse_chord_engraver.cpp
src/graphic_model/lomse_box_slice.cpp
src/graphic_model/lomse_box_slice_instr.cpp
src/graphic_model/lomse_box_system.cpp
src/graphic_model/lomse_caret_positioner.cpp
src/graphic_model/lomse_graphical_model.cpp
src/graphic_model/lomse_timegrid_table.cpp
src/internal_model/lomse_im_measures_table.cpp
src/internal_model/lomse_internal_model.cpp
src/internal_model/lomse_model_builder.cpp
src/internal_model/lomse_score_algorithms.cpp
src/mvc/lomse_interactor.cpp
src/tests/lomse_test_interactor.cpp
src/tests/lomse_the_test_runner.cpp

This PR adds a method to get info about the score object at mouse click point position. It returns a struct `ClickPointData` that describes the content of the point on current bitmap rendition.
The struct provides a ptr. to the clicked object, and if the clicked point is on a score, it also provides:
- A `MeasureLocator` struct with information about measure, instrument, and time position.
- The staff index, relative to instrument staves.
Otherwise, if clicked point is not on a score, the `MeasureLocator` is invalid and the staff index is -1.
Example:
```
//get mouse click point
Pixels x = Pixels( mouse_x );
Pixels y = Pixels( mouse_y );
//get information about that point
ClickPointData data = spInteractor->find_click_info_at(x, y);
ImoObj* pClickedObj = data.pImo;
MeasureLocator ml = …
```

Interactor: API method to get info about mouse click point

---

include/lomse_im_note.h
include/lomse_internal_model.h
include/private/lomse_internal_model_p.h
src/exporters/lomse_mxl_exporter.cpp
src/internal_model/lomse_im_note.cpp
src/sound/lomse_midi_table.cpp
src/tests/lomse_test_midi_table.cpp

Lomse internal model distinguishes between elements used for sound information and elements used for notation information.
For display, visibility of any note is controlled by methods `is_visible()` and `set_visible()`. But for playback there is not any method to mute a note as all this was waiting to implement playback techniques.
This PR adds methods `ImoNote::mute()` and `ImoNote::is_muted()` to control notes playback. In preparation for the future implementation of playback techniques, method `ImoNote::mute(EMuteType value)` receives as parameter not a boolean but a value from enum `EMuteType` that defines different mute techniques. For now, any value different from `k_mute_off` causes to suppress playback for the affected note.
MIDI events generation has been reviewed to ensure that …

Add mute information to notes and suppress playback for muted notes

---

include/lomse_mxl_exporter.h
include/private/lomse_internal_model_p.h
src/exporters/lomse_mxl_exporter.cpp
src/internal_model/lomse_model_builder.cpp
src/parser/ldp/lomse_ldp_analyser.cpp
src/parser/mxl/lomse_mxl_analyser.cpp
src/tests/lomse_test_ldp_analyser.cpp
src/tests/lomse_test_ldp_exporter.cpp
src/tests/lomse_test_mxl_exporter.cpp
test-scores/unit-tests/grace-notes/228-grace-slash.xml
test-scores/unit-tests/xml-export/004-cue-note.xml
test-scores/unit-tests/xml-export/005-octave-shift.xml
test-scores/unit-tests/xml-export/008-pedal-line.xml
test-scores/unit-tests/xml-export/009-pedal-line-marks.xml
test-scores/unit-tests/xml-export/010-pedal-lines.xml
test-scores/unit-tests/xml-export/011-sound-midi-info.xml
test-scores/unit-tests/xml-export/012-directive-moved-to-note.xml
test-scores/unit-tests/xml-export/013-key-number.xml

This PR improves the MusicXML exporter and now exports all the Lomse supported notation. And after this PR the exporter will be totally usable and should produce good results.
Two things are left for the next iteration:
1. Some details related to attributes, such as those common to most elements, such as `%font;` or `%print-style-align;`, are not exported and require a systematic review of all elements.
2. For finishing the exporter I would like first to develop some "round-trip" import-export automatic tests so that I can easily spot issues to fix.

Improve MusicXML exporter

---

src/exporters/lomse_mxl_exporter.cpp
src/tests/lomse_test_mxl_exporter.cpp
test-scores/unit-tests/xml-export/020-single-voice-cross-staff.xml
test-scores/unit-tests/xml-export/021-single-voice-cross-staff-clef-change.xml

This PR fixes all issues detected in MusicXML import/export round-trip automated tests:
- fingering: attributes 'substitution' and 'alternate' were not exported. Fixed.
- wavy-line: currently not enough information is imported and thus, export is incorrect. Import suppressed for now. 
- tremolo: type and number of marks were not exported. Fixed.
- issue with key signatures incorrectly exported when clef change. Fixed.
- issue with cross-staff beams and cross-staff chords. Fixed.
All scores from Lilypond test suite pass now the import/export round-trip automated tests.

Improve MusicXML exporter (3)

---

include/private/lomse_document_p.h
src/document/lomse_command.cpp
src/tests/lomse_test_command.cpp

Undo/redo operations did not mark the document as dirty. As a result, the graphical model was not updated and, apart from being incorrect, this caused crashes on some occasions. This PR fixes this bug.

Fix bug in undo/redo

---

examples/samples/viewtypes/README.md
examples/samples/viewtypes/viewtypes-wx.cpp
src/mvc/lomse_graphic_view.cpp

This PR fixes a bug in `FreeFlowView` which caused the rendering buffer to be painted white when the scale factor (zoom) was changed.
It also updates the sample `viewtypes` that could not be built after PR #371

Fix bug in FreeFlowView when zooming

---

docs/api/doxyfile
docs/api/mainpages/overview.h
include/lomse_box_system.h
include/lomse_gm_basic.h
include/lomse_shape_base.h
include/lomse_shape_staff.h
src/graphic_model/lomse_box_system.cpp
src/tests/lomse_test_graphic_model.cpp
test-scores/unit-tests/other/04-multimetric.lms

This PR adds a new method `GmoBoxSystem::get_num_measures()` and also adds more API documentation for `GmoBoxSystem` and some other `GmoObj` objects .

Add method get_num_measures() and more documentation

---

src/graphic_model/engravers/lomse_wedge_engraver.cpp

Without this the following error occurs when compiling with gcc 12.2.0:
```
src/graphic_model/engravers/lomse_wedge_engraver.cpp:
In member function 'lomse::LUnits lomse::WedgeEngraver::determine_default_shape_position_left(bool) const':
src/graphic_model/engravers/lomse_wedge_engraver.cpp:242:39: error: 'numeric_limits' is not a member of 'std'
242 |     constexpr LUnits xMaxValue = std::numeric_limits<LUnits>::max();
|                                       ^~~~~~~~~~~~~~
src/graphic_model/engravers/lomse_wedge_engraver.cpp:242:60: error: expected primary-expression before '>' token
242 |     constexpr LUnits xMaxValue = std::numeric_limits<LUnits>::max();
|                                                            ^
src/graphic_model/engravers/lomse_wedge_engraver.cpp:242:66: error: no …
```

Add missing include for limits

---

include/lomse_beam_engraver.h
src/graphic_model/engravers/lomse_beam_engraver.cpp
src/parser/mxl/lomse_mxl_analyser.cpp

This pull request contains patches necessary to support cross-system beams, which fixes #388 and other similar crashes. With these patches the relevant systems from the score referenced in #388 looks like this (note the beam between the last note of the first system and the first note of the second system):
Apart from the changes that implement rendering cross-system beams, this pull request also improves importing cross-measure beams from MusicXML. Presence of cross-measure beams may lead to having multiple beams simultaneously open when parsing a MusicXML document, which can lead, without these changes, to some beams being mixed up:

Fix importing and rendering cross-system beams

---

.github/workflows/build-PR.yml
CHANGELOG.md
cmake-modules/FindUnitTest++.cmake
include/lomse_beam_engraver.h
include/lomse_chord_engraver.h
src/graphic_model/engravers/lomse_beam_engraver.cpp
src/graphic_model/engravers/lomse_chord_engraver.cpp
src/graphic_model/layouters/lomse_score_layouter.cpp
src/tests/lomse_test_beam_engraver.cpp
src/tests/lomse_test_chord_engraver.cpp
test-scores/00301-color-inheritance-stems-beams.lms

This PR implements color inheritance for stems, flags and beams (any source format, LDP, MusicXML,...), and closes #393. It also clarifies the color inheritance criteria for stems, flags and beams when color has not been explicitly specified for them in the source file:
_Stems and flags are always rendered in the default color (black) unless the source file specifies a color. When the stem color has not been explicitly specified, the stem and the flag are rendered in the same color as the notehead._
_For a chord, when color has not been explicitly defined in the source file for the stem and flag, they are rendered in the same color as all the noteheads, but if the noteheads do not all have the same color, stem and flag are rendered in the default color (black)._
_For the beam that joins a …

Fix color inheritance for stems, flags and beams

---

CMakeLists.txt
src/render/lomse_font_freetype.cpp

2 small fixes:
- In order to include the library through CMake package managers such as [CPM](https://github.com/cpm-cmake/CPM.cmake), the `CMakeLists.txt` should use `${PROJECT_SOURCE_DIR}` and `${PROJECT_BINARY_DIR}` instead of `${CMAKE_SOURCE_DIR}` and `${CMAKE_BINARY_DIR}` respectively.
- Since commit [`044d142`](https://github.com/freetype/freetype/commit/044d142be7b6a93b6940367a1bc5847451ff4775) of freetype, the tags in `FT_Outline` are now of type `unsigned char*`, which should be echoed in `lomse_font_freetype.cpp`.

Support include through CMake Package Manager + Fix recent breaking change in freetype
